# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170121_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(max_length=230, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
